### ISSUE TITLE
Create docker container for installation

### ISSUE THREAD

**Issue by lucylw** [NCBI-Hackathons/phenotypeXpression#34]

**Comment by rbutleriii** [comment]
A larger issue surfaced during docker creation, related (I think) to #43 . Got a `ImportError: Failed to import any qt binding` similar to:

https://github.com/matplotlib/matplotlib/issues/11929 

Neither `python-pyqt5` or `libgl1-mesa-glx` worked to solve, but manually pointing the backend to the right location did via:

https://stackoverflow.com/questions/35737116/runtimeerror-invalid-display-variable#_=_

Added `plt.switch_backend('agg')` at phenox/phenox.py line 7

**Comment by rbutleriii** [comment]
Correction, also need the `libgl1-mesa-glx` in the docker image. If users are having the same errors they will need OS specific `mesa-libGL` libraries. Per the stackoverflow above it is a hard issue to solve.

Anyways, Dockerfile built.
